### ISSUE TITLE
npm run generate / plop / strict mode

### ISSUE THREAD

**Issue by pierrenel** [react-boilerplate/react-boilerplate#1446]
## Description

Did a fresh install, trying to run a generator, getting:

```
$ npm run generate route

> react-boilerplate@3.3.3 generate /Users/pierre/Code/foo
> plop --plopfile internals/generators/index.js "route"

/Users/pierre/Code/foo/internals/generators/component/index.js:35
    let componentTemplate;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pierre/Code/foo/internals/generators/index.js:8:28)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```

## Steps to reproduce

git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git
npm run clean
npm run generate route

# Versions

- Node/NPM: v5.4.0 / 3.8.5
- Browser: none

**Comment by gihrig** [comment]
@pierrenel Sorry you're running into this.

>SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode.

From your Steps to Reproduce, it looks like you neglected to install dependencies `npm run setup' or just `yarn/npm install`. I will assume that is just an omission in the post and that you did actually run this.

Sounds like webpack/babel is failing to transpile ES6 code. I don't have any real insight into why this would happen, but try this and see if that fixes it.

- Install [Yarn](https://yarnpkg.com/en/docs/install) (if you have not already)
- Delete `node_modules` folder.
- `yarn install`

Then try again.

**Comment by mrhwick** [comment]
I'm also seeing this issue. Here are the steps that I took before seeing this error.

```
brew update
brew install yarn
git clone --depth=1 https://github.com/mxstbr/react-boilerplate.git
cd react-boilerplate
npm run setup
npm run clean
npm run generate
```

**Comment by gihrig** [comment]
I don't see this on Mac OS 10.11 and current `dev` branch.

What OS and  version of react-boilerplate are you guys running?

**Comment by mrhwick** [comment]
![image](https://cloud.githubusercontent.com/assets/865759/21944168/ba9d6f1a-d9a2-11e6-83c0-992a0b4177ee.png)

Using `master` branch

**Comment by mrhwick** [comment]
I don't know what the real fix should be, but I edited the block in question to include `"use strict";`. After that, the command `npm run generate` appears to be working for me.

That was just inside of [this block](https://github.com/mxstbr/react-boilerplate/blob/master/internals/generators/component/index.js#L33)

**Comment by gihrig** [comment]
This is a totally wild guess, but it's weird enough that, hey, why not...

There have been some odd issues that came up relating libs on Mac OS see this [discussion](https://github.com/mxstbr/react-boilerplate/pull/1322#issuecomment-266264527).

We have worked through those issues, and are ready to release the next update, 3.4. I'm curious to know how that works for you. But be advised, it's a big change, be sure to read the change log if you have any previous react-boilerplate code. If you're just getting started, 3.4 is the place to start.

**Comment by gretzky** [comment]
Closing due to inactivity
