### ISSUE TITLE
Error on npm run build (clean installation)

### ISSUE THREAD

**Issue by mistre833** [react-boilerplate/react-boilerplate#1651]
## Description

In a clean installation, when i run `npm run build` i go this error output: (i have a similar error on `npm run start:production`)

```
Hash: d47ffd438aa443fba8c2                                                               
Version: webpack 2.2.0-rc.3
Time: 12807ms
                          Asset       Size  Chunks             Chunk Names
                      .htaccess    1.79 kB          [emitted]  
                    favicon.ico     370 kB          [emitted]  
                  manifest.json  624 bytes          [emitted]  
0.b9dfddf96ba25b5c1910.chunk.js    41.4 kB       0  [emitted]  
1.51a0e47b2daae8250036.chunk.js    2.04 kB       1  [emitted]  
2.c669071dfbfca3acf1e5.chunk.js    2.02 kB       2  [emitted]  
3.20d0e2989b358867fdd4.chunk.js    24.1 kB       3  [emitted]  
   main.4d5cdc73b219c6bef2da.js     652 kB       4  [emitted]  main
                     index.html  558 bytes          [emitted]  
                          sw.js    15.9 kB          [emitted]  
[./app/app.js] ./app/app.js 4.41 kB {4} [built]
[./app/containers/LanguageProvider/index.js] ./app/containers/LanguageProvider/index.js 3.78 kB {4} [built]
[./app/global-styles.js] ./app/global-styles.js 1.25 kB {4} [built]
[./app/i18n.js] ./app/i18n.js 1.24 kB {4} [built]
[./app/routes.js] ./app/routes.js 2.17 kB {4} [built]
[./app/store.js] ./app/store.js 2.12 kB {4} [built]
[./node_modules/babel-polyfill/lib/index.js] ./~/babel-polyfill/lib/index.js 833 bytes {4} [built]
[./node_modules/file-loader/index.js?name=[name].[ext]!./app/.htaccess] ./~/file-loader?name=[name].[ext]!./app/.htaccess 55 bytes {4} [built]
[./node_modules/file-loader/index.js?name=[name].[ext]!./app/favicon.ico] ./~/file-loader?name=[name].[ext]!./app/favicon.ico 57 bytes {4} [built]
[./node_modules/intl/index.js] ./~/intl/index.js 574 bytes {0} [built]
[./node_modules/intl/locale-data/jsonp/en.js] ./~/intl/locale-data/jsonp/en.js 24 kB {3} [built]
[./node_modules/offline-plugin/runtime.js] ./~/offline-plugin/runtime.js 719 bytes {4} [built]
[./node_modules/react-router-scroll/lib/index.js] ./~/react-router-scroll/lib/index.js 512 bytes {4} [built]
[./node_modules/sanitize.css/sanitize.css] ./~/sanitize.css/sanitize.css 864 bytes {4} [built]
   [1] multi main 28 bytes {4} [built]
    + 662 hidden modules

ERROR in ./~/css-loader!./~/sanitize.css/sanitize.css
Module build failed: Error: ENOENT: no such file or directory, open '/home/mistre83/Projects/react-boilerplate/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.fs.openSync (fs.js:583:18)
    at Object.fs.readFileSync (fs.js:490:33)
    at module.exports (/home/mistre83/Projects/react-boilerplate/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/home/mistre83/Projects/react-boilerplate/node_modules/svgo/lib/svgo.js:21:19)
    at /home/mistre83/Projects/react-boilerplate/node_modules/postcss-svgo/dist/index.js:91:16
    at Object.creator [as postcssSvgo] (/home/mistre83/Projects/react-boilerplate/node_modules/postcss/lib/postcss.es6:111:27)
    at /home/mistre83/Projects/react-boilerplate/node_modules/cssnano/dist/index.js:286:40
    at Array.forEach (native)
    at /home/mistre83/Projects/react-boilerplate/node_modules/cssnano/dist/index.js:273:29
    at creator (/home/mistre83/Projects/react-boilerplate/node_modules/postcss/lib/postcss.es6:111:27)
    at processCss (/home/mistre83/Projects/react-boilerplate/node_modules/css-loader/lib/processCss.js:187:16)
    at Object.module.exports (/home/mistre83/Projects/react-boilerplate/node_modules/css-loader/lib/loader.js:24:2)
 @ ./~/sanitize.css/sanitize.css 4:14-66
 @ ./app/app.js
 @ multi main
Child __offline_serviceworker:
    [./node_modules/exports-loader/index.js?self.fetch!./node_modules/whatwg-fetch/fetch.js] ./~/exports-loader?self.fetch!./~/whatwg-fetch/fetch.js 12.6 kB {0} [built]
    [./node_modules/offline-plugin/empty-entry.js] ./~/offline-plugin/empty-entry.js 0 bytes {0} [built]
    [./node_modules/offline-plugin/lib/misc/sw-loader.js?json=%7B%22data_var_name%22%3A%22__wpo%22%2C%22loaders%22%3A%5B%5D%2C%22cacheMaps%22%3A%5B%5D%7D!./node_modules/offline-plugin/empty-entry.js] ./~/offline-plugin/lib/misc/sw-loader.js?json=%7B%22data_var_name%22%3A%22__wpo%22%2C%22loaders%22%3A%5B%5D%2C%22cacheMaps%22%3A%5B%5D%7D!./~/offline-plugin/empty-entry.js 16.2 kB {0} [built]
Child html-webpack-plugin for "index.html":
    [./node_modules/html-webpack-plugin/lib/loader.js!./app/index.html] ./~/html-webpack-plugin/lib/loader.js!./app/index.html 502 bytes {0} [built]

npm ERR! Linux 4.8.0-41-generic
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v7.7.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! react-boilerplate@3.4.0 build: `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.4.0 build script 'cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mistre83/Projects/react-boilerplate/npm-debug.log

```

## Steps to reproduce

`npm run setup`
`npm run clean`
`npm run build` 

# Versions

- React-Boilerplate: `3.4.0`
- Node/NPM:` 6.10.0/3.10.10`
- SO: `Ubuntu 16.0`

**Comment by gihrig** [comment]
@mistre833 Try [this](https://github.com/react-boilerplate/react-boilerplate/blob/dev/docs/general/gotchas.md#when-in-doubt-re-install)

**Comment by mahinshaw** [comment]
I get the same issue when I run `yarn clean` at any point. I fixed this by removing the instances of `.*.yml` and `*.yml` from the `.yarnclean` file.  This keeps the `yarn clean` command from cleaning out yaml files from the node_modules, which is the issue for this failure.

**Comment by sureshHARDIYA** [comment]
Didn't really help. still getting the same error. 
```
ERROR in ./node_modules/css-loader!./node_modules/sanitize.css/sanitize.css
Module build failed: Error: ENOENT: no such file or directory, open '/Users/sureshkumarmukhiya/Code/landed-backend/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Object.fs.openSync (fs.js:652:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at module.exports (/Users/sureshkumarmukhiya/Code/landed-backend/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/Users/sureshkumarmukhiya/Code/landed-backend/node_modules/svgo/lib/svgo.js:21:19)
    at /Users/sureshkumarmukhiya/Code/landed-backend/node_modules/postcss-svgo/dist/index.js:95:16
    at Object.creator [as postcssSvgo] (/Users/sureshkumarmukhiya/Code/landed-backend/node_modules/postcss/lib/postcss.es6:111:27)
    at /Users/sureshkumarmukhiya/Code/landed-backend/node_modules/cssnano/dist/index.js:295:40
    at Array.forEach (<anonymous>)
    at /Users/sureshkumarmukhiya/Code/landed-backend/node_modules/cssnano/dist/index.js:282:29
    at creator (/Users/sureshkumarmukhiya/Code/landed-backend/node_modules/postcss/lib/postcss.es6:111:27)
    at processCss (/Users/sureshkumarmukhiya/Code/landed-backend/node_modules/css-loader/lib/processCss.js:199:16)
    at Object.module.exports (/Users/sureshkumarmukhiya/Code/landed-backend/node_modules/css-loader/lib/loader.js:40:2)
 @ ./node_modules/sanitize.css/sanitize.css 4:14-64
 @ ./app/app.js
 @ multi ./app/app.js```

**Comment by gihrig** [comment]
@sureshHARDIYA I've had a lot of trouble with yarn recently and npm in the past. I would try manually running `npm install` with the latest npm. 

You can update npm to latest with `npm i -g npm`.

**Comment by gretzky** [comment]
Closing due to inactivity
