### ISSUE TITLE
Heroku Deployment Failing

### ISSUE THREAD

**Issue by sujeshkumaruv** [react-boilerplate/react-boilerplate#1779]
I am unable to deploy to Heroku following the steps in the heroku deployment guidelines. However , I was able to deploy the original boilerplate to Heroku at

(https://mymedisquare1.herokuapp.com/.

Subsequent deployment after changing the content of the react-boilerplate fails. When I try and push the changes to heroku , the deployment fails. I am commenting the error log from Heroku. 

Can anyone brief me the cause? It is to be noted that I can run the program in my local machine.
 
Thanks.

**Comment by sujeshkumaruv** [comment]
I was to able to deploy the react-boilerplate to Heroku  but after subsequently building a application , I am not able to push changes to Heroku. 




-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  >=5
       engines.npm (package.json):   >=3
       
       Resolving node version >=5 via semver.io...
       Downloading and installing node 7.10.0...
       Resolving npm version >=3 via semver.io...
       Downloading and installing npm 4.6.1 (replacing version 4.2.0)...
       Resolving yarn version (latest) via semver.io...
       Downloading and installing yarn (0.24.5)...
       Installed yarn 0.24.5
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v0.24.5
       $ npm run npmcheckversion
       
       > react-boilerplate@3.4.0 npmcheckversion /tmp/build_c990fe8490c51f83ff00f43c89a6d60b
       > node ./internals/scripts/npmcheckversion.js
       
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
       info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning "eslint-import-resolver-webpack@0.8.0" has incorrect peer dependency "webpack@^1.11.0 || ^2.1.0-beta || ^2.1.0".
       warning "html-webpack-plugin@2.24.1" has incorrect peer dependency "webpack@1 || ^2.1.0-beta".
       [4/4] Building fresh packages...
       $ npm run build:dll
       
       > react-boilerplate@3.4.0 build:dll /tmp/build_c990fe8490c51f83ff00f43c89a6d60b
       > node ./internals/scripts/dependencies.js
       
       Done in 36.06s.
       Running heroku-postbuild (yarn)
       yarn run v0.24.5
       $ npm run build
       
       > react-boilerplate@3.4.0 prebuild /tmp/build_c990fe8490c51f83ff00f43c89a6d60b
       > npm run build:clean
       
       
       > react-boilerplate@3.4.0 build:clean /tmp/build_c990fe8490c51f83ff00f43c89a6d60b
       > npm run test:clean && rimraf ./build
       
       
       > react-boilerplate@3.4.0 test:clean /tmp/build_c990fe8490c51f83ff00f43c89a6d60b
       > rimraf ./coverage
       
       
       > react-boilerplate@3.4.0 build /tmp/build_c990fe8490c51f83ff00f43c89a6d60b
       > cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress
       
       Hash: e769490f987a09d70cec
       Version: webpack 2.2.0-rc.3
       Time: 26889ms
       Asset       Size  Chunks             Chunk Names
       3.5c031638b91ed5b23616.chunk.js    41.4 kB       3  [emitted]
       1817761c72bb7cf289ea72034edc70e6.jpg    13.5 kB          [emitted]
       favicon.ico     370 kB          [emitted]
       manifest.json  624 bytes          [emitted]
       0.21c4fa6dca474d378fbc.chunk.js     132 kB       0  [emitted]
       1.9eb4454225097361fce4.chunk.js    41.9 kB       1  [emitted]
       2.b40f59abd75aa6cfc2c0.chunk.js    34.9 kB       2  [emitted]
       .htaccess    1.79 kB          [emitted]
       4.a53b3d517ccf188c35ca.chunk.js     1.1 kB       4  [emitted]
       5.eca9e7f6fc5dfb0624e7.chunk.js  617 bytes       5  [emitted]
       6.3f552873be2a7815cc20.chunk.js    24.1 kB       6  [emitted]
       7.72f8c829811afedd278d.chunk.js    24.4 kB       7  [emitted]
       main.a3dff7a7f37fcede2902.js     709 kB       8  [emitted]  main
       index.html  646 bytes          [emitted]
       sw.js    16.4 kB          [emitted]
       [./app/app.js] ./app/app.js 4.93 kB {8} [built]
       [./app/containers/App/index.js] ./app/containers/App/index.js 2.35 kB {8} [built]
       [./app/containers/App/selectors.js] ./app/containers/App/selectors.js 1.58 kB {8} [built]
       [./app/containers/LanguageProvider/index.js] ./app/containers/LanguageProvider/index.js 3.68 kB {8} [built]
       [./app/global-styles.js] ./app/global-styles.js 6.03 kB {8} [built]
       [./app/i18n.js] ./app/i18n.js 1.43 kB {8} [built]
       [./app/routes.js] ./app/routes.js 2.82 kB {8} [built]
       [./app/store.js] ./app/store.js 2.12 kB {8} [built]
       [./node_modules/babel-polyfill/lib/index.js] ./~/babel-polyfill/lib/index.js 833 bytes {8} [built]
       [./node_modules/react-dom/index.js] ./~/react-dom/index.js 59 bytes {8} [built]
       [./node_modules/react-redux/lib/index.js] ./~/react-redux/lib/index.js 475 bytes {8} [built]
       [./node_modules/react-router-redux/lib/index.js] ./~/react-router-redux/lib/index.js 1.97 kB {8} [built]
       [./node_modules/react-router-scroll/lib/index.js] ./~/react-router-scroll/lib/index.js 512 bytes {8} [built]
       [./node_modules/react-router/es/index.js] ./~/react-router/es/index.js 1.46 kB {8} [built]
       [1] multi main 28 bytes {8} [built]
       + 804 hidden modules
       
       ERROR in ./app/containers/AddAppointment/index.js
       Module not found: Error: Can't resolve './Section' in '/tmp/build_c990fe8490c51f83ff00f43c89a6d60b/app/containers/AddAppointment'
       @ ./app/containers/AddAppointment/index.js 35:0-32
       @ ./app/routes.js
       @ ./app/app.js
       @ multi main
       
       ERROR in ./app/components/Header/index.js
       Module not found: Error: Can't resolve './Navbar' in '/tmp/build_c990fe8490c51f83ff00f43c89a6d60b/app/components/Header'
       @ ./app/components/Header/index.js 26:0-30
       @ ./app/containers/App/index.js
       @ ./app/app.js
       @ multi main
       
       ERROR in ./app/containers/HomePage/patient.png
       Module build failed: Error: spawn /tmp/build_c990fe8490c51f83ff00f43c89a6d60b/node_modules/pngquant-bin/vendor/pngquant ENOENT
       at exports._errnoException (util.js:1050:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
       at onErrorNT (internal/child_process.js:367:16)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9)
       @ ./app/containers/HomePage/index.js 40:0-39
       @ ./app/routes.js
       @ ./app/app.js
       @ multi main
       
       ERROR in ./app/containers/HomePage/Appointments.png
       Module build failed: Error: spawn /tmp/build_c990fe8490c51f83ff00f43c89a6d60b/node_modules/pngquant-bin/vendor/pngquant ENOENT
       at exports._errnoException (util.js:1050:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
       at onErrorNT (internal/child_process.js:367:16)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9)
       @ ./app/containers/HomePage/index.js 42:0-49
       @ ./app/routes.js
       @ ./app/app.js
       @ multi main
       
       ERROR in ./app/containers/HomePage/consultation.png
       Module build failed: Error: spawn /tmp/build_c990fe8490c51f83ff00f43c89a6d60b/node_modules/pngquant-bin/vendor/pngquant ENOENT
       at exports._errnoException (util.js:1050:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
       at onErrorNT (internal/child_process.js:367:16)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9)
       @ ./app/containers/HomePage/index.js 41:0-49
       @ ./app/routes.js
       @ ./app/app.js
       @ multi main
       
       ERROR in ./app/containers/HomePage/add.png
       Module build failed: Error: spawn /tmp/build_c990fe8490c51f83ff00f43c89a6d60b/node_modules/pngquant-bin/vendor/pngquant ENOENT
       at exports._errnoException (util.js:1050:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
       at onErrorNT (internal/child_process.js:367:16)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9)
       @ ./app/containers/HomePage/index.js 43:0-32
       @ ./app/routes.js
       @ ./app/app.js
       @ multi main
       
       ERROR in ./app/components/RightPanel/calendar.png
       Module build failed: Error: spawn /tmp/build_c990fe8490c51f83ff00f43c89a6d60b/node_modules/pngquant-bin/vendor/pngquant ENOENT
       at exports._errnoException (util.js:1050:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
       at onErrorNT (internal/child_process.js:367:16)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9)
       @ ./app/components/RightPanel/index.js 18:0-38
       @ ./app/components/Header/index.js
       @ ./app/containers/App/index.js
       @ ./app/app.js
       @ multi main
       
       ERROR in ./app/components/RightPanel/menu.png
       Module build failed: Error: spawn /tmp/build_c990fe8490c51f83ff00f43c89a6d60b/node_modules/pngquant-bin/vendor/pngquant ENOENT
       at exports._errnoException (util.js:1050:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
       at onErrorNT (internal/child_process.js:367:16)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9)
       @ ./app/components/RightPanel/index.js 19:0-30
       @ ./app/components/Header/index.js
       @ ./app/containers/App/index.js
       @ ./app/app.js
       @ multi main
       
       ERROR in ./app/components/Logo/logo-mobile.png
       Module build failed: Error: spawn /tmp/build_c990fe8490c51f83ff00f43c89a6d60b/node_modules/pngquant-bin/vendor/pngquant ENOENT
       at exports._errnoException (util.js:1050:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
       at onErrorNT (internal/child_process.js:367:16)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9)
       @ ./app/components/Logo/index.js 21:0-46
       @ ./app/components/Header/index.js
       @ ./app/containers/App/index.js
       @ ./app/app.js
       @ multi main
       
       ERROR in ./app/components/NotificationStatus/notification.png
       Module build failed: Error: spawn /tmp/build_c990fe8490c51f83ff00f43c89a6d60b/node_modules/pngquant-bin/vendor/pngquant ENOENT
       at exports._errnoException (util.js:1050:11)
       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
       at onErrorNT (internal/child_process.js:367:16)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9)
       @ ./app/components/NotificationStatus/index.js 22:0-49
       @ ./app/components/StatusBar/index.js
       @ ./app/containers/HomePage/index.js
       @ ./app/routes.js
       @ ./app/app.js
       @ multi main
       Child html-webpack-plugin for "index.html":
       [./node_modules/html-webpack-plugin/lib/loader.js!./app/index.html] ./~/html-webpack-plugin/lib/loader.js!./app/index.html 591 bytes {0} [built]
       Child __offline_serviceworker:
       [./node_modules/exports-loader/index.js?self.fetch!./node_modules/whatwg-fetch/fetch.js] ./~/exports-loader?self.fetch!./~/whatwg-fetch/fetch.js 12.6 kB {0} [built]
       [./node_modules/offline-plugin/empty-entry.js] ./~/offline-plugin/empty-entry.js 0 bytes {0} [built]
       [./node_modules/offline-plugin/lib/misc/sw-loader.js?json=%7B%22data_var_name%22%3A%22__wpo%22%2C%22loaders%22%3A%5B%5D%2C%22cacheMaps%22%3A%5B%5D%7D!./node_modules/offline-plugin/empty-entry.js] ./~/offline-plugin/lib/misc/sw-loader.js?json=%7B%22data_var_name%22%3A%22__wpo%22%2C%22loaders%22%3A%5B%5D%2C%22cacheMaps%22%3A%5B%5D%7D!./~/offline-plugin/empty-entry.js 16.2 kB {0} [built]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! react-boilerplate@3.4.0 build: `cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the react-boilerplate@3.4.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2017-05-27T08_15_09_065Z-debug.log
error Command failed with exit code 2.
       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       


       - This project was built with yarn, which is new and under development. Some projects can still be built more reliably with npm
       https://devcenter.heroku.com/articles/nodejs-support#build-behavior
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by IamJoseph** [comment]
You can run the app locally but can you build locally without errors? If so please run `npm run start:production` and make sure there are no errors. Do you have a Procfile? If the answer is yes to all of those if I had to guess I'd say either 
a) you're trying to use a module that doesn't exist in ./app/containers/AddAppointment/index.js 35:0-32 and ./app/components/Header/index.js
b) the path is incorrect
c) there is an error in your webpack config.

**Comment by magiccookie** [comment]
I had this issue both locally and in deployment. Here's how I solved it:

1. Update `image-webpack-loader`
2. Specify node version. For me it was

```
  "engines": {
    "npm": "3.10.x",
    "node": "6.10.3"
  }
```

FYI my config for images

```
      test: /\.(jpg|png|gif)$/,
      loaders: [
        'file-loader',
        {
          loader: 'image-webpack-loader',
          query: {
            mozjpeg: {
              progressive: true,
            },
            optipng: {
              optimizationLevel: 7,
            },
            gifsicle: {
              interlaced: false,
            },
            pngquant: {
              quality: '65-90',
              speed: 4,
            },
          },
        },
      ]
```

**Comment by gretzky** [comment]
Closing due to inactivity
