### ISSUE TITLE
npm run start - Unexpected token in JSON at position 1040 

### ISSUE THREAD

**Issue by arpanvaidya** [react-boilerplate/react-boilerplate#1786]
## Description
Just set up react boilerplate. Running into the following issue after ```npm run start``` command

```
> react-boilerplate@3.4.0 start /vagrant_code/react-boilerplate
> cross-env NODE_ENV=development node server

Server started ! ✓

Access URLs:
-----------------------------------
Localhost: http://localhost:3000
      LAN: http://10.0.2.15:3000
-----------------------------------
Press CTRL-C to stop
    
(node:1719) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
webpack built 347e1814544b8c54e340 in 24652ms

ERROR in ./~/css-loader!./~/sanitize.css/sanitize.css
Module build failed: SyntaxError: /vagrant_code/react-boilerplate/node_modules/caniuse-db/features-json/text-emphasis.json: Unexpected token  in JSON at position 1040
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/vagrant_code/react-boilerplate/node_modules/autoprefixer/data/prefixes.js:622:11)
    at Object.<anonymous> (/vagrant_code/react-boilerplate/node_modules/autoprefixer/data/prefixes.js:669:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
 @ ./~/sanitize.css/sanitize.css 4:14-64 13:2-17:4 14:20-70
 @ ./app/app.js
 @ multi main
Child html-webpack-plugin for "index.html":
```

**Comment by gretzky** [comment]
Closing due to inactivity
