### ISSUE TITLE
How to add await/async to boilerplate

### ISSUE THREAD

**Issue by pengyanb** [react-boilerplate/react-boilerplate#1891]
I am struggling with add 'await/async' support to the bolilerplate at the moment.
I found similar question [#1481](https://github.com/react-boilerplate/react-boilerplate/issues/1481). I was following the exact same steps as described in #1481 :
1. install package by running 
`npm install --save-dev babel-plugin-transform-async-to-generator`
2. In my package.json I added
```javascript
"babel": {
    "presets": [
      [
        "latest",
        {
          "es2015": {
            "modules": false
          }
        }
      ],
      "react",
      "stage-0"
    ],
    "env": {
      "production": {
        "only": ["app"],
        "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-constant-elements",
          "transform-react-inline-elements",
          "transform-async-to-generator"
        ]
      },
      "test": {
        "plugins": ["transform-es2015-modules-commonjs", "dynamic-import-node"]
      }
    }
  },
```
 Async/Await code section:  
```javascript
User.statics.isEmailAddressRegistered = async (emailToVerify) => {
  try {
    const document = await this.findOne({ userEmail: emailToVerify })
      .select({ userEmail: 1, _id: 0 })
      .exec();
    .....
```
I am getting error as follow: 
```javascript
User.statics.isEmailAddressRegistered = async (
                                              ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

I also tried to modify my package.json to the following, but still getting the same error:
```javascript
"babel": {
    "presets": [
      [
        "latest",
        {
          "es2015": {
            "modules": false
          }
        }
      ],
      "react",
      "stage-0"
    ],
    "env": {
      "production": {
        "only": ["app"],
        "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-constant-elements",
          "transform-react-inline-elements",
          "transform-async-to-generator"
        ]
      },
      "development":{
        "plugins":["transform-async-to-generator"]
      },
      "test": {
        "plugins": ["transform-es2015-modules-commonjs", "dynamic-import-node"]
      }
    }
  },
```

Can anyone give me a hand and point me the right direction? Do I need to modify any files in the `internals/webpack/` folder?
Thanks a lot in advance.

**Comment by gretzky** [comment]
Hey there, looks like this isn't an issue with react-boilerplate. If you're looking for help, check out [StackOverflow](https://stackoverflow.com) and post your question there.
