### ISSUE TITLE
Error: Cannot find module 'shelljs'

### ISSUE THREAD

**Issue by Sokal21** [react-boilerplate/react-boilerplate#1971]
I clone the repo and follow the instructions to start de boilerplate example but I keep getting this error when I run "npm run setup"

> Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\TomasLopez\Projects\BurningManagment\react-boilerplate\internals\scripts\setup.js:5:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.5.0 setup: `node ./internals/scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.5.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TomasLopez\AppData\Roaming\npm-cache\_logs\2017-10-08T21_11_12_229Z-debug.log

**Comment by gretzky** [comment]
Closing due to inactivity
