### ISSUE TITLE
Adding redux-form breaks test - Path must be a string. Received undefined

### ISSUE THREAD

**Issue by et** [react-boilerplate/react-boilerplate#1992]
## Issue Type

- [x] Bug

## Description

I can successfully use `redux-form` within my app, but I get a weird cryptic errors with the test suite after adding it. This is really easy to replicate as all you need to do is add `redux-form` to the `package.json` file.

```
 FAIL  app/components/LoadingIndicator/tests/index.test.js
  ● Test suite failed to run

    TypeError: Path must be a string. Received undefined

      at assertPath (path.js:28:11)
      at Object.relative (path.js:1247:5)

 FAIL  app/components/Header/tests/index.test.js
  ● Test suite failed to run

    TypeError: Path must be a string. Received undefined

      at assertPath (path.js:28:11)
      at Object.relative (path.js:1247:5)
```

## Steps to reproduce

`git clone --depth=1 https://github.com/react-boilerplate/react-boilerplate.git`
`cd react-boilerplate`
`npm run setup`
`yarn add redux-form`
`npm test # observe errors`
# Versions

- React-Boilerplate (see `package.json`): 3.5.0
- Node/NPM: v8.0.0/5.4.1
- Browser: Chrome

**Comment by gretzky** [comment]
Closing due to inactivity. Feel free to reopen.

**Comment by et** [comment]
This is still an issue. Please reopen.

**Comment by gretzky** [comment]
@et can you send over a test repo showing the issue?

**Comment by gretzky** [comment]
@et can you open up a test repo showing the issue? I just followed your steps to replicate and all test suites passed and returned ok.

**Comment by sourcesoft** [comment]
I couldn't reproduce the error, it passed all the tests after installing redux-form on a fresh clone.

Remove node_modules, clear cache and upgrade to latest `jest-cli` to see if it works now.
