### ISSUE TITLE
[Eslint] Error: Couldn't find preset "airbnb" relative to directory

### ISSUE THREAD

**Issue by kavimaluskam** [react-boilerplate/react-boilerplate#2108]
No build error is found but error found in Webstorm:

Using Mac v10.12.6, Webstorm 2017.3.2
```
Error: Cannot read config file: /Users/garki/projects/react-boilerplate/node_modules/eslint-config-airbnb/index.js
Error: Couldn't find preset "airbnb" relative to directory "/Users/garki/projects/react-boilerplate/node_modules/eslint-config-airbnb"
Referenced from: /Users/garki/projects/react-boilerplate/package.json

Error: Cannot read config file: /Users/garki/projects/react-boilerplate/node_modules/eslint-config-airbnb/index.js
Error: Couldn't find preset "airbnb" relative to directory "/Users/garki/projects/react-boilerplate/node_modules/eslint-config-airbnb"
Referenced from: /Users/garki/projects/react-boilerplate/package.json
    at /Users/garki/projects/react-boilerplate/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/garki/projects/react-boilerplate/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/garki/projects/react-boilerplate/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/garki/projects/react-boilerplate/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/garki/projects/react-boilerplate/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/garki/projects/react-boilerplate/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/garki/projects/react-boilerplate/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/garki/projects/react-boilerplate/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
Process finished with exit code -1
```

**Comment by blling** [comment]
You can try to delete `node_modules` and reinstall

**Comment by kavimaluskam** [comment]
Thanks @blling , but i have tried several times but still in veins.

I have also tried `npm install --save-dev babel-preset-airbnb` and got the below error
```
Error: There was a problem loading formatter: ./formatters/json
Error: Options {"loose":true} passed to /Users/garki/projects/react-boilerplate/node_modules/babel-preset-env/lib/index.js which does not accept options. (While processing preset: "/Users/garki/projects/react-boilerplate/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/Users/garki/projects/react-boilerplate/node_modules/babel-preset-env/lib/index.js")

Error: There was a problem loading formatter: ./formatters/json
Error: Options {"loose":true} passed to /Users/garki/projects/react-boilerplate/node_modules/babel-preset-env/lib/index.js which does not accept options. (While processing preset: "/Users/garki/projects/react-boilerplate/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/Users/garki/projects/react-boilerplate/node_modules/babel-preset-env/lib/index.js")
    at /Users/garki/projects/react-boilerplate/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:314:17
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/garki/projects/react-boilerplate/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/garki/projects/react-boilerplate/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/garki/projects/react-boilerplate/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/garki/projects/react-boilerplate/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/garki/projects/react-boilerplate/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/garki/projects/react-boilerplate/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/garki/projects/react-boilerplate/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
Process finished with exit code -1
```

**Comment by stelioschar** [comment]
I faced it in Webstorm 2017.3.* This is a webstorm issue. In Webstorm 2017.2 works fine. Downgrade or submit an issue to Webstorm team

**Comment by kavimaluskam** [comment]
Thanks @stelioschar . Looks true and probably i shall close the issue on this side.

**Comment by Mensae** [comment]
@kavimaluskam this is indeed a Webstorm issue, see [ticket](https://youtrack.jetbrains.com/issue/WEB-30457)
