### ISSUE TITLE
EsLint couldn't find the plugin "eslint-plugin-html"

### ISSUE THREAD

**Issue by dungla4** [react-boilerplate/react-boilerplate#2173]
## Description

There's an error when run `yarn run lint` or `npm run lint`:
```
EsLint couldn't find the plugin "eslint-plugin-html".
```

## Steps to reproduce

- Clone react-boilerplate project with command `git clone --depth=1 https://github.com/react-boilerplate/react-boilerplate.git`
- Run command to setup: `npm run setup`
- Enter to remove old repo
- Run linting: `yarn run lint` then get issue below:
```
$ yarn run lint
yarn run v1.5.1
$ npm run lint:js

> react-boilerplate@3.5.0 lint:js /Users/dungla4/workspace/app-react-boilerplate
> npm run lint:eslint -- .


> react-boilerplate@3.5.0 lint:eslint /Users/dungla4/workspace/app-react-boilerplate
> eslint --ignore-path .gitignore --ignore-pattern internals/scripts "."


Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-html". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-html is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-html@latest --save-dev
```
Actually we don't use `eslint-plugin-html` for react project, this error is too strange. However I try to install `eslint-plugin-html` (latest is 4.0.2)
After installing, I got another issue:
```
$ yarn run lint
yarn run v1.5.1
$ npm run lint:js

> react-boilerplate@3.5.0 lint:js /Users/dungla4/workspace/app-react-boilerplate
> npm run lint:eslint -- .


> react-boilerplate@3.5.0 lint:eslint /Users/dungla4/workspace/app-react-boilerplate
> eslint --ignore-path .gitignore --ignore-pattern internals/scripts "."

eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
Error: eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
    at iterateESLintModules (/Users/dungla4/workspace/app-react-boilerplate/node_modules/eslint-plugin-html/src/index.js:65:11)
    at Object.<anonymous> (/Users/dungla4/workspace/app-react-boilerplate/node_modules/eslint-plugin-html/src/index.js:26:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.load (/Users/dungla4/workspace/app-react-boilerplate/node_modules/eslint/lib/config/plugins.js:129:26)
```

# Versions

- React-Boilerplate (see `package.json`): 3.5.0
- Node/NPM: v9.10.1/5.6.0
- Browser: N/A

I also tried to downgrade node to v8 but same error
There's no `eslint` global (yarn and npm)

**Comment by gretzky** [comment]
Can you paste the contents of your `.eslintrc`?

**Comment by dungla4** [comment]
@gretzky There's no `.eslintrc` in my project (also in my home folder)

**Comment by gretzky** [comment]
Are you using the same `eslintConfig` inside of `package.json` that comes standard with this bp? Or is any of it different?

**Comment by dungla4** [comment]
I found the root cause :(
There's an `.eslintrc` in parent folder of my project. That's why eslint always notify error.  After deleting file, everything is ok.
Close this issue. Thank you very much @gretzky
