### ISSUE TITLE
Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

### ISSUE THREAD

**Issue by ShaneMcX** [react-boilerplate/react-boilerplate#2178]
Side note: the links on Bug and Feature in the template are 404.

- [X] Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [X] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description
I think this is actually a bug because the boilerplate features should be compatible, but the fix is likely a feature request. As far as I can gather, Enzyme's render and React-Intl don't play well together, resulting in the error in the title. I found corroboration, discussion, and workarounds here:
https://stackoverflow.com/questions/36866363/testing-react-intl-components-with-enzyme
and here:
https://gist.github.com/mirague/c05f4da0d781a9b339b501f1d5d33c37

It would be great if this (or another) workaround could be part of the boilerplate so that enzyme rendering of components with FormattedMessage elements will succeed without having to choose between partially-tested workarounds found on the web.

## Steps to reproduce

This is trivial to repro. Just use 'render' instead of 'shallow' in any component with FormattedMessages. I was very surprised not to find an issue with this, but perhaps everyone who hits it is just using one of the workarounds at the links above? Is there a better solution?

1. Clone react-boilerplate, setup, clean, etc.
2. In containers/HomePage/tests/index.test.js, replace 'shallow' with 'render' (or copy/paste from here)
```javascript
import React from 'react';
import { FormattedMessage } from 'react-intl';
import { render } from 'enzyme';

import HomePage from '../index';
import messages from '../messages';

describe('<HomePage />', () => {
  it('should render the page message', () => {
    const renderedComponent = render(<HomePage />);
    expect(
      renderedComponent.contains(<FormattedMessage {...messages.header} />)
    ).toEqual(true);
  });
});
```

3. yarn test

result:
```
FAIL  app/containers/HomePage/tests/index.test.js
  ● <HomePage /> › should render the page message

    Invariant Violation: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

      at invariant (node_modules/invariant/invariant.js:42:15)
      at invariantIntlContext (node_modules/react-intl/lib/index.js:357:5)
      at new FormattedMessage (node_modules/react-intl/lib/index.js:1409:9)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:294:18
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
      at ReactCompositeComponentWrapper._constructComponentWithoutOwner (node_modules/react-dom/lib/ReactCompositeComponent.js:293:16)
      at ReactCompositeComponentWrapper._constructComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:279:21)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:187:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:45:35)
      at ReactDOMComponent.mountChildren (node_modules/react-dom/lib/ReactMultiChild.js:236:44)
      at ReactDOMComponent._createContentMarkup (node_modules/react-dom/lib/ReactDOMComponent.js:659:32)
      at ReactDOMComponent.mountComponent (node_modules/react-dom/lib/ReactDOMComponent.js:526:29)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:45:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:370:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:45:35)
      at node_modules/react-dom/lib/ReactServerRendering.js:45:36
      at ReactServerRenderingTransaction.perform (node_modules/react-dom/lib/Transaction.js:143:20)
      at renderToStringImpl (node_modules/react-dom/lib/ReactServerRendering.js:43:24)
      at renderToStaticMarkup (node_modules/react-dom/lib/ReactServerRendering.js:83:10)
      at render (node_modules/enzyme/build/render.js:91:52)
      at Object.<anonymous> (app/containers/HomePage/tests/index.test.js:10:48)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

# Versions

- React-Boilerplate (see `package.json`): 3.5.0
- Node/NPM: 5.6.0
- Browser: N/A (but Version 65.0.3325.181 (Official Build) (64-bit))

**Comment by ShaneMcX** [comment]
I see now that this is documented on react-intl's github. Would be nice to at least add a link and brief description of the workaround to react-boilerplate's troubleshooting page, since anyone writing interesting tests is likely to hit it.

https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#enzyme
https://medium.com/@sapegin/testing-react-intl-components-with-jest-and-enzyme-f9d43d9c923e

**Comment by ShaneMcX** [comment]
I see also that the sample app uses <IntlProvider>, which works for mount but does not appear to work for render.

**Comment by ShaneMcX** [comment]
I came across one more solution: enzyme-react-intl. Not sure whether it does anything more than \<IntlProvider\>.
https://github.com/joetidee/enzyme-react-intl
