### ISSUE TITLE
Resolve alias in Jest not working

### ISSUE THREAD

**Issue by dariospadoni** [react-boilerplate/react-boilerplate#2253]
## Issue Type

- Bug (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#bug-reports)

## Description

I'm having same problem described here https://github.com/react-boilerplate/react-boilerplate/issues/1580 with last version of the boilerplate.
I can't re-open/comment the previous issue so I'm creating a new one.

## Steps to reproduce
- create a  folder named `config` inside `app` with 2 files in it, `development.js` and `test.js` first one being just 
```
module.exports = {
  projectName: 'development',
};
```
second being
```
module.exports = {
  projectName: 'test',
};
```
- add the following alias inside `resolve` in `webpack.base.babel.js` pointing to the newly created file:
```
alias: {
      config: path.join(process.cwd(), `app/config/${process.env.NODE_ENV}.js`),
},
```

- reference this alias, for example inside the `FeaturePage` by adding `import config from 'config';` on top of the file and `<H1>{config.projectName}</H1>` within the `render` method.

- run the project (`npm start`) and open feature page: text `development` text is shown within the `H1` block. 

- run test (`npm run test`); all the tests will pass but one returning:

```
FAIL  app/containers/FeaturePage/tests/index.test.js
  ● Test suite failed to run

    Cannot find module 'config' from 'index.js'



      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:210:17)
      at Object.<anonymous> (app/containers/FeaturePage/index.js:111:41)
```

# Versions

- React-Boilerplate: 3.6.0
- Node/NPM: 5.6.0
- Browser:

**Comment by gretzky** [comment]
Thanks for filling out the issue template! 

I ran your steps to reproduce and couldn't produce the same error. Can you confirm you're resolving it correctly? 

I ask because of the err you're getting.

```
Cannot find module 'config' from 'index.js'
```

You should be importing config in `index.test.js` like this

```
import config from '../index'
```

If not that, double check all of your code because I couldn't reproduce it on my end.

**Comment by dariospadoni** [comment]
I forked the repository, you can clone it from https://github.com/dariospadoni/react-boilerplate/ and `npm run test` to reproduce the issue

**Comment by dariospadoni** [comment]
It looks fixed, I just add to update `jest-cli` to last version...

**Comment by gretzky** [comment]
Interesting. Thanks for dropping this, I'll keep an eye out for any other related issues and see if an update to jest-cli is merited

**Comment by dariospadoni** [comment]
Actually, I noticed that in my several attempts, I also added 
```
"config$": "<rootDir>/app/config/test.js"
```
to `moduleNameMapper` within jest config in `package.json`. If I remove this, I still get the same error.

**Comment by gretzky** [comment]
@julienben can you replicate this? I couldn't, but I definitely think it might be something.

**Comment by dariospadoni** [comment]
If this can help replication, you can clone the repo https://github.com/dariospadoni/react-boilerplate/ 
 which I forked. Running `npm run test` will cause the error, adding `"config$": "<rootDir>/app/config/test.js"` will fix it (using `"jest-cli": "23.1.0")

**Comment by julienben** [comment]
I won't have time to look into this in detail right now but could you try fixing it with this:

```js
{
  alias: {
    path.resolve(__dirname, `app/config/${process.env.NODE_ENV}.js`),
  }
}
```

**Comment by dariospadoni** [comment]
No it does not fix, ```"config$": "<rootDir>/app/config/test.js"``` is still needed

**Comment by sugatmahanti** [comment]
I have the same issue but in CI (Jekins) . It works locally. I have tried all sorts of combination for `moduleNameMapper` in jest package.json and `config` `alias` in webpack. It still says could not find module `config`.
