### ISSUE TITLE
argv is not defined when running npm start

### ISSUE THREAD

**Issue by joe-fenton** [react-boilerplate/react-boilerplate#2308]
#Bug

## Description

When I run npm start I get the following error:
> cross-env NODE_ENV=development node server

C:\dev\Source\test\site\server\index.js:6
  (isDev && process.env.ENABLE_TUNNEL) || argv.tunnel
                                          ^

ReferenceError: argv is not defined
    at Object.<anonymous> (C:\dev\Source\test\site\server\index.js:6:43)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.1.0 start: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1

It previously worked, all I have done is restart my computer.

I have tried removing node_modules and rerunning npm install, npm build:dll, etc.
I have checked and the argv.js file exists as does the minimalist package it uses.

# Versions

- React-Boilerplate (see `package.json`): 3.6.0
- Node/NPM: 8.9.4
- Browser:

**Comment by joe-fenton** [comment]
Sorry, I discovered it was a VS Code sorting require/imports that caused the problem.
