### ISSUE TITLE
Change relative path in .eslintrc.js to absolute path

### ISSUE THREAD

**Issue by heyrict** [react-boilerplate/react-boilerplate#2356]
# Description

I'm using vim with ale plugin to edit the js files, but it complains about not finding `./.prettier.rc` until I modifies the `.eslitrc.js` file. The fix is shown below. Maybe we should add this?

```diff
 const fs = require('fs');
+const path = require('path');
 
-const prettierOptions = JSON.parse(fs.readFileSync('./.prettierrc', 'utf8'));
+const prettierOptions = JSON.parse(
+  fs.readFileSync(path.join(__dirname, '.prettierrc'), 'utf8'),
+);
 
 module.exports = {
   parser: 'babel-eslint',
```

# Versions

- React-Boilerplate (see `package.json`): v3.6.0 (and the latest master branch).

**Comment by gretzky** [comment]
I also use Vim with ale and have no issue, I can almost bet its your ale config

**Comment by heyrict** [comment]
Well, I will close this issue as it seems like something related to the ale plugin as it cannot automatically change to project root correctly.
I'm still struggling to make ale plugin work without modifying `.eslint.js` file.

My :ALEInfo output is shown below. @yuchaosydney 
```
  ALEInfo
 Current Filetype: javascript.jsx
Available Linters: ['eslint', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint']
 Suggested Fixers:
  'eslint' - Apply eslint --fix to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript files using xo --fix.
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'typescript.jsx': ['prettier'], 'typescript': ['prettier'], 'json': ['prettier'], 'javascript': ['prettier'], 'css': ['prettier'],
 'python': ['isort', 'yapf']}
let g:ale_history_enabled = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'typescript.jsx': ['eslint'], 'typescript': ['eslint'], 'html': ['tidy'], 'javascript': ['eslint']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) /home/heyrict/Eric/MyPrograms/django/cindy/react-boilerplate/node_modules/eslint/bin/eslint.js
(finished - exit code 1) ['/bin/bash', '-c', '''/home/heyrict/Eric/MyPrograms/django/cindy/react-boilerplate/node_modules/eslint/bin/eslint.js'' -f un
ix --stdin --stdin-filename ''/home/heyrict/Eric/MyPrograms/django/cindy/react-boilerplate/app/containers/App/index.js'' < ''/tmp/vGY4Gf2/3/index.js''
']
<<<OUTPUT STARTS>>>
Cannot read config file: /home/heyrict/Eric/MyPrograms/django/cindy/react-boilerplate/.eslintrc.js
Error: ENOENT: no such file or directory, open './.prettierrc'
Error: Cannot read config file: /home/heyrict/Eric/MyPrograms/django/cindy/react-boilerplate/.eslintrc.js
Error: ENOENT: no such file or directory, open './.prettierrc'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.<anonymous> (/home/heyrict/Eric/MyPrograms/django/cindy/react-boilerplate/.eslintrc.js:3:39)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
<<<OUTPUT ENDS>>>
```

**Comment by heyrict** [comment]
I've tested vim with all plugin disabled except ale with all default configurations, but still without success.

I'm still not sure if this is an issue of ale or eslint or something else.
Running eslint (or editing a file with vim) from path other than project root will raise an error.

```
Error: Cannot read config file: /path/to/react-boilerplate/.eslintrc.js
Error: ENOENT: no such file or directory, open './.prettierrc'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.<anonymous> (/path/to/react-boilerplate/.eslintrc.js:8:39)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

Could you provide more information about your environment? (e.g. Command History section in :ALEInfo output)

**Comment by julienben** [comment]
This change was already added in #2286 (for an unrelated reason) and will make it into the next version.
