### ISSUE TITLE
Error on run deploy

### ISSUE THREAD

**Issue by raisiqueira** [react-boilerplate/react-boilerplate#2369]
Hi, i'm trying to deploy the RB to the [WeDeploy](https://wedeploy.com), but are returning this error:

```bash
Oct 06 20:12:31.643 [arvfront] Build in progress [homolog] as nodejs…
Oct 06 20:12:34.123 homolog[build] Step 1/12 : FROM node:10.11.0
Oct 06 20:12:34.124 homolog[build]  ---> 8672b25e842c
Oct 06 20:12:34.124 homolog[build] Step 2/12 : RUN curl -o- -L https://yarnpkg.com/install.sh | bash
Oct 06 20:12:34.126 homolog[build]  ---> Using cache
Oct 06 20:12:34.126 homolog[build]  ---> 213b28f3b6f8
Oct 06 20:12:34.126 homolog[build] Step 3/12 : ENV WEDEPLOY_APP_DIRECTORY /wedeploy/app/
Oct 06 20:12:34.127 homolog[build]  ---> Using cache
Oct 06 20:12:34.127 homolog[build]  ---> 30ec4858df41
Oct 06 20:12:34.127 homolog[build] Step 4/12 : RUN mkdir -p $WEDEPLOY_APP_DIRECTORY
Oct 06 20:12:34.128 homolog[build]  ---> Using cache
Oct 06 20:12:34.128 homolog[build]  ---> c240176f507c
Oct 06 20:12:34.128 homolog[build] Step 5/12 : WORKDIR $WEDEPLOY_APP_DIRECTORY
Oct 06 20:12:34.129 homolog[build]  ---> Using cache
Oct 06 20:12:34.129 homolog[build]  ---> a5164091a9b0
Oct 06 20:12:34.129 homolog[build] Step 6/12 : COPY package.json package-lock.json* yarn.lock* $WEDEPLOY_APP_DIRECTORY
Oct 06 20:12:34.535 homolog[build]  ---> 1f6e8a3850cb
Oct 06 20:12:34.535 homolog[build] Step 7/12 : RUN yarn install
Oct 06 20:12:34.580 homolog[build]  ---> Running in a2b29d3af95e
Oct 06 20:12:35.236 homolog[build] yarn install v1.9.4
Oct 06 20:12:35.460 homolog[build] $ npm run npmcheckversion
Oct 06 20:12:35.786 homolog[build] 
> arvmed-web@0.1.0 npmcheckversion /wedeploy/app
> node ./internals/scripts/npmcheckversion.js

Oct 06 20:12:35.866 homolog[build] internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/wedeploy/app/internals/scripts/npmcheckversion.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
Oct 06 20:12:35.870 homolog[build] npm ERR! code ELIFECYCLE
Oct 06 20:12:35.870 homolog[build] npm ERR! errno 1
Oct 06 20:12:35.871 homolog[build] npm ERR! arvmed-web@0.1.0 npmcheckversion: `node ./internals/scripts/npmcheckversion.js`
npm ERR! Exit status 1
Oct 06 20:12:35.871 homolog[build] npm ERR! 
npm ERR! Failed at the arvmed-web@0.1.0 npmcheckversion script.
npm ERR!
Oct 06 20:12:35.872 homolog[build]  This is probably not a problem with npm. There is likely additional logging output above.
Oct 06 20:12:35.874 homolog[build] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
Oct 06 20:12:35.875 homolog[build] 
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-06T23_12_35_873Z-debug.log
Oct 06 20:12:35.880 homolog[build] error Command failed with exit code 1.
Oct 06 20:12:35.880 homolog[build] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Oct 06 20:12:36.163 homolog[build] The command '/bin/sh -c yarn install' returned a non-zero code: 1
Oct 06 20:12:36.163 homolog[build] Something went wrong and the entire build was interrupted due to incorrect configuration file or build step, check your source code. {"errorDetail":{"code":1,"message":"The command '/bin/sh -c yarn install' returned a non-zero code: 1"},"error":"The command '/bin/sh -c yarn install' returned a non-zero code: 1"}
Oct 06 20:12:36.219 [arvfront] Some error has happened during the build. Try again. [{"message":"Bad Request","status":400,"errors":[{"reason":"runtimeBuildError","context":{"details":"{\"errorDetail\":{\"code\":1,\"message\":\"The command '/bin/sh -c yarn install' returned a non-zero code: 1\"},\"error\":\"The command '/bin/sh -c yarn install' returned a non-zero code: 1\"}","message":"Something went wrong and the entire build was interrupted due to incorrect configuration file or build step, check your source code."}}]}].

```

**Comment by satishjhanwer** [comment]
@raisiqueira I believe you are using `Docker` for creating the build then you are missing one step which is `Copy` of the internal folder onto your work dir inside docker before triggering `yarn or npm install`.

```
ADD internals $WEDEPLOY_APP_DIRECTORY/internals
```

**Comment by raisiqueira** [comment]
I'm testing with `node:8.12-alpine`. I'm going to test with the `node:8.12` only.

**Comment by raisiqueira** [comment]
Ok, work fine with `ENTRYPOINT` command instead `CMD` for start:prod. This is my Dockerfile:

```Dockerfile
FROM node:8.12
LABEL com.arvoremed.version="0.1.0"

WORKDIR /app

ADD package.json /app
ADD internals/ /app
RUN npm install
COPY . /app
EXPOSE 3000
RUN npm run build
ENTRYPOINT npm run start:prod
```
