### ISSUE TITLE
Error: Cannot find module "node-sass"

### ISSUE THREAD

**Issue by sharmavikram** [react-boilerplate/react-boilerplate#2471]
**Hello All**,

i am trying to build react project in development mode it is showing "node-sass" error.

**node Version: v8.11.2
npm Version: v5.6.0**

Here is my error:-
`ERROR in ./src/scss/style.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/scss/style.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (/var/www/html/react-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.sassLoader (/var/www/html/react-boilerplate/node_modules/sass-loader/lib/loader.js:46:72)
 @ ./src/scss/style.scss 2:14-123 21:1-42:3 22:19-128
 @ ./src/Bootstrap.jsx
 @ multi react-hot-loader/patch webpack-dev-server/client?http://localhost:3060 webpack/hot/only-dev-server ./src/Bootstrap
`

I have already used the below command but not works.

**npm rebuild node-sass
npm rebuild node-sass --force
npm rebuild** 

Please help...

Thanks,
**Vikram**

**Comment by julienben** [comment]
As the bot says, this issue was closed because you didn't fill out the issue template.
