### ISSUE TITLE
installation problem.

### ISSUE THREAD

**Issue by pgee70** [react-boilerplate/react-boilerplate#2493]
## Description
The initial installation does not proceed as i thought it would.
## Steps to reproduce
```
git clone --depth=1 https://github.com/react-boilerplate/react-boilerplate.git  sap
Cloning into 'sap'...
remote: Enumerating objects: 393, done.
remote: Counting objects: 100% (393/393), done.
remote: Compressing objects: 100% (336/336), done.
remote: Total 393 (delta 71), reused 196 (delta 34), pack-reused 0
Receiving objects: 100% (393/393), 1.11 MiB | 1.66 MiB/s, done.
Resolving deltas: 100% (71/71), done.
cd sap

npm run setup
> react-boilerplate@3.7.0 presetup /opt/local/www/apache2/html/sap
> npm i chalk shelljs


> fsevents@1.2.4 install /opt/local/www/apache2/html/sap/node_modules/fsevents
> node install

[fsevents] Success: "/opt/local/www/apache2/html/sap/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> pre-commit@1.2.2 install /opt/local/www/apache2/html/sap/node_modules/pre-commit
> node install.js


> spawn-sync@1.0.15 postinstall /opt/local/www/apache2/html/sap/node_modules/spawn-sync
> node postinstall


> cwebp-bin@4.0.0 postinstall /opt/local/www/apache2/html/sap/node_modules/cwebp-bin
> node lib/install.js

  ✔ cwebp pre-build test passed successfully

> gifsicle@3.0.4 postinstall /opt/local/www/apache2/html/sap/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> mozjpeg@5.0.0 postinstall /opt/local/www/apache2/html/sap/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /opt/local/www/apache2/html/sap/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> pngquant-bin@5.0.0 postinstall /opt/local/www/apache2/html/sap/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully

> ngrok@3.1.0 postinstall /opt/local/www/apache2/html/sap/node_modules/ngrok
> node ./postinstall.js

ngrok - cached download found at /Users/pgee/.ngrok/aHR0cHM6Ly9iaW4uZXF1aW5veC5pby9jLzRWbUR6QTdpYUhiL25ncm9rLXN0YWJsZS1kYXJ3aW4tYW1kNjQuemlw.zip
ngrok - unpacking binary
ngrok - binary unpacked to /opt/local/www/apache2/html/sap/node_modules/ngrok/bin/ngrok

> styled-components@4.0.2 postinstall /opt/local/www/apache2/html/sap/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
(node:67581) Warning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
+ chalk@2.4.1
+ shelljs@0.8.2
added 1976 packages in 51.432s

> react-boilerplate@3.7.0 setup /opt/local/www/apache2/html/sap
> node ./internals/scripts/setup.js

/opt/local/www/apache2/html/sap/internals/scripts/setup.js:22
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.7.0 setup: `node ./internals/scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.7.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pgee/.npm/_logs/2018-11-26T02_02_18_442Z-debug.log

```
## Versions
npm --version
5.6.0

**Comment by pgee70** [comment]
sorry had old versions of node/npm installed.
