### ISSUE TITLE
Enzyme Test on generated Connected Container Fails

### ISSUE THREAD

**Issue by akshayKrSingh** [react-boilerplate/react-boilerplate#2628]
## Description
Generated a Container using Plop, with 'yes' to all options -> **saga**, **store**, **reducers**, **selectors**, then ran the tests for the container to test if Formatted Message renders properly, the test is failing:

##### ContainerPage
```bash
export class ContainerPage extends React.PureComponent {
  render() {
    const { classes } = this.props;

    return (
      <div className={classes.root}>
        <Helmet>
          <title>ContainerPage</title>
          <meta name="description" content="Description of ContainerPage" />
        </Helmet>
        <FormattedMessage {...messages.header} />
      </div>
    );
  }
}

ContainerPage.propTypes = {
  dispatch: PropTypes.func.isRequired,
  classes: PropTypes.object.isRequired,
};

const mapStateToProps = createStructuredSelector({
  containerPage: makeSelectContainerPage(),
});

function mapDispatchToProps(dispatch) {
  return {
    dispatch,
  };
}

const withConnect = connect(
  mapStateToProps,
  mapDispatchToProps,
);

const withReducer = injectReducer({ key: 'containerPage', reducer });
const withSaga = injectSaga({ key: 'containerPage', saga });

export default compose(
  withReducer,
  withSaga,
  withConnect,
  withStyles(styles),
)(ContainerPage);
```

##### ContainerPage Test
```bash
import React from 'react';
import { FormattedMessage } from 'react-intl';
import { shallow } from 'enzyme';

import configureStore from '../../../configureStore';
import ContainerPage from '../index';
import messages from '../messages';

describe('<ContainerPage />', () => {
  it('should render the page message', () => {
    const renderedComponent = shallow(<ContainerPage store={configureStore({})} />).dive().dive().dive().dive();
    expect(renderedComponent.contains(<FormattedMessage {...messages.header} />)).toEqual(true);
  });
});
```

##### Error
```bash
Invariant Violation: (app/utils...) injectors: Expected a valid redux store

      15 |     injectedSagas: isObject,
      16 |   };
    > 17 |   invariant(conformsTo(store, shape), '(app/utils...) injectors: Expected a valid redux store');
         |   ^
      18 | }
      19 | 

      at invariant (node_modules/invariant/invariant.js:40:15)
      at invariant (app/utils/checkStore.js:17:3)
```

## Steps to reproduce
1. Just generated a Container Component using RBP generators, with `yes` to all options.
2. Wrote the test to validate if `<FormattedMessage />` exists on the rendered page.
3. When running the test, if throws an error during initialization due to invalid redux store.

**Expected behavior**
The test should have passed.

## Versions

- React-Boilerplate: `3.7.0`
- Node/NPM: `node @11.12.0` `npm @6.9.0`
- Browser: n / a

**Comment by akshayKrSingh** [comment]
ahh ok.... yup working now. thanks @julienben !!
