### ISSUE TITLE
Cannot find module 'lodash/defaultsDeep' after upgrading React

### ISSUE THREAD

**Issue by RonenA** [react-boilerplate/react-boilerplate#2850]
## Description
I'm getting the following error when running npm install:
```
Error: Cannot find module 'lodash/defaultsDeep'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/ronen/Dropbox/Projects/alysia/lyric-studio/internals/scripts/dependencies.js:13:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```
I've seen a couple other bug reports, and I've tried deleting the node_modules and reinstalling as has been suggested. This project was working fine and able to build before this.

## Steps to reproduce
Before this occurred, I upgraded React to 16.8.0. Could this be related?

## Versions

- React-Boilerplate: 3.6.0
- Node/NPM: node 10.16.3, npm 5.0.3

**Comment by Can-Sahin** [comment]
I downloaded the version `3.6.0` and upgraded react to `16.8.0` and everything is working. No `npm install` errors. 

Can you provide a sample repository reproducing the error?

(maybe also try deleting `package-lock.json` and `node_modules` together if you haven't tried that already)

**Comment by RonenA** [comment]
Looks like deleting package-lock.json fixed it 🤦‍♂ Thank you!
