### ISSUE TITLE
Updating React-boiler package.json causing errors

### ISSUE THREAD

**Issue by zulqarnain-26** [react-boilerplate/react-boilerplate#2990]
I updated packages.json file to latest  and it is causing issues in react.intl and webpack-dev-middleware   .
errors: 
TypeError: Cannot read property 'readFile' of undefined
    at app.get (react-boilerplate/server/middlewares/addDevMiddlewares.js:30:8)
    
    Module not found: Error: Can't resolve 'react-intl/locale-data/en' in '/react-boilerplate/app'
    
    
Any help will be appreciated.

**Comment by zulqarnain-26** [comment]
I updated packages.json file to latest and it is causing issues in react.intl and webpack-dev-middleware .
errors:
TypeError: Cannot read property 'readFile' of undefined
at app.get (react-boilerplate/server/middlewares/addDevMiddlewares.js:30:8)

Module not found: Error: Can't resolve 'react-intl/locale-data/en' in '/react-boilerplate/app'
Any help will be appreciated.
