### ISSUE TITLE
Upgrading to react & react-dom v 17.0.2 breaks useInjectSaga & useInjectReducer tests

### ISSUE THREAD

**Issue by ctangell** [react-boilerplate/react-boilerplate#3011]
## Description
After upgrading to react & react-dom v 17.0.2, the tests for `useInjectSaga` and `useInjectReducer` fail.  Curiously the tests for the decorator version pass. The effect in the hook is also being called correctly, as tested by dropping a console.log in it and looking for the output of it.

## Steps to reproduce

Upgrade to react@17.0.2 and react-dom@17.0.2

run tests.

**Expected behavior**
The tests should pass.

**Screenshots**
```
Summary of all failing tests
 FAIL  app/utils/tests/injectReducer.test.js
  ● useInjectReducer hook › should inject a given reducer

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      93 |     );
      94 | 
    > 95 |     expect(injectors.injectReducer).toHaveBeenCalledTimes(1);
         |                                     ^
      96 |     expect(injectors.injectReducer).toHaveBeenCalledWith('test', reducer);
      97 |   });
      98 | });

      at Object.<anonymous> (app/utils/tests/injectReducer.test.js:95:37)

 FAIL  app/utils/tests/injectSaga.test.js
  ● useInjectSaga hook › should inject given saga and mode

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      128 |     );
      129 | 
    > 130 |     expect(injectors.injectSaga).toHaveBeenCalledTimes(1);
          |                                  ^
      131 |     expect(injectors.injectSaga).toHaveBeenCalledWith('test', {
      132 |       saga: testSaga,
      133 |       mode: 'testMode',

      at Object.<anonymous> (app/utils/tests/injectSaga.test.js:130:34)

  ● useInjectSaga hook › should eject on unmount with a correct saga key

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      144 |     unmount();
      145 | 
    > 146 |     expect(injectors.ejectSaga).toHaveBeenCalledTimes(1);
          |                                 ^
      147 |     expect(injectors.ejectSaga).toHaveBeenCalledWith('test');
      148 |   });
      149 | });

      at Object.<anonymous> (app/utils/tests/injectSaga.test.js:146:33)
```
## Versions

- React-Boilerplate: latest
- Node/NPM: yarn 1.22.10
- Browser:

**Comment by ctangell** [comment]
I should note that upgrading to a newer version of React is essential for us since we need the async `act` for testing component updates, so not upgrading is not really an option.

And I verified this bug exists on a clean version of react-boilerplate, not just on our project.

**Comment by ljmerza** [comment]
I hate to break it to you, but this boilerplate has been deprecated for a long time now. The new repo is here https://github.com/react-boilerplate/react-boilerplate-cra-template

**Comment by ctangell** [comment]
Good to know.  For those still on the legacy boilerplate, and need to upgrade their version of `react`, we were able to do so by grabbing the versions of `injectReducer.js` and `injectSaga.js` from [redux-injectors](https://github.com/react-boilerplate/redux-injectors)

**Comment by nelsonfncosta** [comment]
Just to share my approach on @ctangell solution.

The update is very straightforward.
Replacing any usage you may have from the previous injectors with the respective counterpart from the `redux-injectors` lib.

ex:
```diff
- import injectSaga from 'utils/injectSaga';
+ import { injectSaga } from 'redux-injectors';
``` 

and update the store creation  in `configureStore.js` with the lib enhancers

my store ex:
```
import { createInjectorsEnhancer } from 'redux-injectors';

  const middlewares = [sagaMiddleware, routerMiddleware(history)];

  const enhancers = [applyMiddleware(...middlewares)];

  const store = createStore(
    createReducer(),
    initialState,
    composeEnhancers(
      ...enhancers,
      createInjectorsEnhancer({
        createReducer,
        runSaga: sagaMiddleware.run,
      }),
    ),
  );
```
