### ISSUE TITLE
npm setup failed: `Error: could not resolve`

### ISSUE THREAD

**Issue by code-by** [react-boilerplate/react-boilerplate#3071]
## Description
I'm new to RBp and try to setup new project.
I'm following setup instructions from this repo, but it failed (

On question `Do you want to start with a new repository? [Y/n] ` I'm select 'Y' and get following:
```
Removing current repository ✓
Installing dependencies... ✓This might take a while)

 ✘ Error: Error: Command failed: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: connected-react-router@6.4.0
npm ERR! Found: react-redux@7.0.2
npm ERR! node_modules/react-redux
npm ERR!   react-redux@"7.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-redux@"^6.0.0" from connected-react-router@6.4.0
npm ERR! node_modules/connected-react-router
npm ERR!   connected-react-router@"6.4.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react-redux@6.0.1
npm ERR! node_modules/react-redux
npm ERR!   peer react-redux@"^6.0.0" from connected-react-router@6.4.0
npm ERR!   node_modules/connected-react-router
npm ERR!     connected-react-router@"6.4.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /mnt/ssd/lib/npm-cache/eresolve-report.txt for a full report.
```

error from log:
```
49 verbose stack Error: could not resolve
49 verbose stack     at PlaceDep.failPeerConflict (/home/x/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:549:25)
49 verbose stack     at PlaceDep.place (/home/x/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:199:21)
49 verbose stack     at new PlaceDep (/home/x/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:73:10)
49 verbose stack     at /home/x/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:944:31
49 verbose stack     at Array.map (<anonymous>)
49 verbose stack     at Arborist.[buildDepStep] (/home/x/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:944:8)
49 verbose stack     at async Arborist.buildIdealTree (/home/x/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:211:7)
49 verbose stack     at async Promise.all (index 1)
49 verbose stack     at async Arborist.reify (/home/x/.nvm/versions/node/v12.21.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
49 verbose stack     at async Install.exec (/home/x/.nvm/versions/node/v12.21.0/lib/node_modules/npm/lib/commands/install.js:145:5)
```

## Steps to reproduce
```
git clone --depth=1 https://github.com/react-boilerplate/react-boilerplate.git myprj
cd myprj
npm run setup
... (press Y/Entrer on first prompt)
```

**Expected behavior**
It must finish w/o errors

**Screenshots**

## Versions

- React-Boilerplate: latest
- Node/NPM: 12.21.0/8.19.2
- Browser: Chrome 106.0.5249.103

**Comment by tausifcreates** [comment]
Do not use this. it's already 3 years old.

**Comment by lqminh268** [comment]
in internals>script>setup.js, change `npm install` to `yarn`, it solve for me.

**Comment by gopi-codingo** [comment]
Are there any updates on this issue. I'm facing the same.

**Comment by Ravinavala** [comment]
I have same issue:

 ✘ Error: Error: Command failed: npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: connected-react-router@6.4.0
npm ERR! Found: react-redux@7.0.2
npm ERR! node_modules/react-redux
npm ERR!   react-redux@"7.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-redux@"^6.0.0" from connected-react-router@6.4.0
npm ERR! node_modules/connected-react-router
npm ERR!   connected-react-router@"6.4.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react-redux@6.0.1
npm ERR! node_modules/react-redux
npm ERR!   peer react-redux@"^6.0.0" from connected-react-router@6.4.0
npm ERR!   node_modules/connected-react-router
npm ERR!     connected-react-router@"6.4.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\KSHMR\AppData\Local\npm-cache\_logs\2023-05-06T15_35_00_980Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\KSHMR\AppData\Local\npm-cache\_logs\2023-05-06T15_35_00_980Z-debug-0.log

Node : v18.16.0
NPM: 9.6.3

**Comment by Arunimchakraborty** [comment]
Faced the same issue. Solved it by running:
 `npm install --legacy-peer-deps`
After that I used 
`npm start `
But it showed me a missing module **lodash.isequalwith** which I installed by running the command:
`npm install --legacy-peer-deps lodash.isequalwith`
After that using npm start works
