### ISSUE TITLE
The DLL files are missing. Sit back while we build them for you with "npm run build-dll"

### ISSUE THREAD

**Issue by ettisafxrup** [react-boilerplate/react-boilerplate#3076]
It was fine moments ago. But when I try to execute the command "yarn start", it thorws this error. Even there is no scripts written with build-dll I found. I looked up at the source code and I found it was running npm run postinstall. I tried o run it manually but it's still stucked!

```
Node.js v19.0.1
[webpack-cli] Failed to load 'D:\Codes\MERN\App\electron-react-boilerplate\.erb\configs\webpack.config.renderer.dev.ts' config
[webpack-cli] Error: Command failed: npm run postinstall
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module './check-native-dep.js'
Require stack:
- D:\Codes\MERN\App\electron-react-boilerplate\.erb\sripts\imaginaryUncacheableRequireResolveScript
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at requireResolveNonCached (D:\Codes\MERN\App\electron-react-boilerplate\node_modules\ts-node\dist\bin.js:549:16)
    at getProjectSearchDir (D:\Codes\MERN\App\electron-react-boilerplate\node_modules\ts-node\dist\bin.js:519:40)
    at phase3 (D:\Codes\MERN\App\electron-react-boilerplate\node_modules\ts-node\dist\bin.js:267:27)
    at bootstrap (D:\Codes\MERN\App\electron-react-boilerplate\node_modules\ts-node\dist\bin.js:47:30)
    at main (D:\Codes\MERN\App\electron-react-boilerplate\node_modules\ts-node\dist\bin.js:33:12)
    at Object.<anonymous> (D:\Codes\MERN\App\electron-react-boilerplate\node_modules\ts-node\dist\bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Codes\\MERN\\App\\electron-react-boilerplate\\.erb\\sripts\\imaginaryUncacheableRequireResolveScript'
  ]
}

Node.js v19.0.1

    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)    
    at Object.<anonymous> (D:\Codes\MERN\App\electron-react-boilerplate\.erb\configs\webpack.config.renderer.dev.ts:38:11)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module.m._compile (D:\Codes\MERN\App\electron-react-boilerplate\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Codes\MERN\App\electron-react-boilerplate\node_modules\ts-node\src\index.ts:1621:12)    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 0a 3e 20 70 6f 73 74 69 6e 73 74 61 6c 6c 0a 3e 20 74 73 2d 6e 6f 64 65 20 2e 65 72 62 2f 73 72 69 70 74 73 2f 63 68 65 63 6b 2d 
6e 61 74 69 76 65 2d ... 174 more bytes>,      
    <Buffer 6e 6f 64 65 3a 69 6e 74 65 72 6e 61 6c 2f 6d 6f 64 75 6c 65 73 2f 63 6a 73 2f 6c 6f 61 64 65 72 3a 39 39 38 0d 0a 20 20 74 68 72 
6f 77 20 65 72 72 3b ... 1301 more bytes>      
  ],
  pid: 10024,
  stdout: <Buffer 0a 3e 20 70 6f 73 74 69 6e 73 74 61 6c 6c 0a 3e 20 74 73 2d 6e 6f 64 65 20 2e 65 72 62 2f 73 72 69 70 74 73 2f 63 68 65 63 6b 2d 6e 61 74 69 76 65 2d ... 174 more bytes>,  stderr: <Buffer 6e 6f 64 65 3a 69 6e 74 
65 72 6e 61 6c 2f 6d 6f 64 75 6c 65 73 2f 63 6a 73 2f 6c 6f 61 64 65 72 3a 39 39 38 0d 0a 20 20 74 68 72 6f 77 20 65 72 72 3b ... 1301 more bytes>}
error Command failed with exit code 2.
```

**Comment by RashvinVrutti** [comment]
do you find the solution? i am also stuck at this problem

**Comment by GA-Testtemp** [comment]
Hi folks - not sure if this helps such an old issue but I just had something fairly similar. I eventually realised that I had moved all the source files to a different folder, and left behind some hidden files and folders in the process. I moved the hidden files and folders as well, and now everything is healing nicely.

**Comment by ettisafxrup** [comment]
I also solved the problem by doing the same thing.
I moved all the files to a different folder except that node modules. then I installed all of them and it worked totally fine!

**Comment by felipellrocha** [comment]
Anyone have more detail on this? I'm running into this issue, but I moved no files. I've no idea how to make progress. What files were moved? From where to where?

**Comment by EmmaUmeh** [comment]
You use windows?? i think i resolved mine have issues too with the .Dll file
